### PR TITLE
Adding Specializations For AutoDiffScalar

### PR DESCRIPTION
**Pull request by m-chaturvedi**
Perhaps there's a better way because I'm delegating all the methods/attributes.
https://github.com/RobotLocomotion/drake/issues/5815

### CODE REVIEW

**Comment by sherm1** [comment]
If you haven't done so already, this PR should be submitted to Eigen also -- hopefully they'll include it in an upcoming release so we don't need to mirror it.

**Comment by jwnimmer-tri** [comment]
The intent of RobotLocomotion/drake#5785 is to fix this _with a change to Drake_ -- i.e., put this code into Drake, not our fork of Eigen.  Changing our fork of Eigen is no better than fixing it upstream and bumping the commit.

**Comment by stonier** [comment]
This still looks like a useful thing to get upstream though to polish the AutoDiffScalar module and so that one day you can eventually turn it off in drake itself.

@m-chaturvedi could probably use a pointer on where to put it. In `drake/common/eigen_autodiff_limits.h` is probably appropriate. @jwnimmer-tri can update if a different location is more advisable.

**Comment by jwnimmer-tri** [comment]
Yes, in `common` somewhere, and that name is fine by me.  And `#include "drake/common/eigen_autodiff_types.h"` should cause this code to be included so that it's always in-scope, so probably that file should just `#include` whatever this new file is.

**Comment by stonier** [comment]
Closing, since it's moving to drake as referenced above.

**Pull request closed without merging**
